name: codechallenge
services:
  redpanda:
    image: redpandadata/redpanda:v24.1.1
    container_name: redpanda1
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - 9092:9092
      - 29092:29092

  console:
    image: docker.redpanda.com/redpandadata/console:v2.5.2
    container_name: redpanda-console1
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - 8090:8080
    depends_on:
      - redpanda

  game-player-1:
    build: .
    container_name: game-player-1
    environment:
      SPRING_PROFILES_ACTIVE: player1
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:29092
    depends_on:
      - redpanda

  game-player-2:
    build: .
    container_name: game-player-2
    environment:
      SPRING_PROFILES_ACTIVE: player2
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:29092
    depends_on:
      - redpanda